FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY MusicExport/*.csproj ./MusicExport/
RUN dotnet restore MusicExport/MusicExport.csproj
COPY MusicExport/. ./MusicExport/
WORKDIR /src/MusicExport
RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/runtime:6.0
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "MusicExport.dll"]