# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_transfer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x64\x61ta_transfer.proto\x12\x0c\x64\x61tatransfer\"j\n\x10MusicDataRequest\x12\x12\n\ngroup_name\x18\x01 \x01(\t\x12\x15\n\rmusician_name\x18\x02 \x01(\t\x12\x17\n\x0finstrument_name\x18\x03 \x01(\t\x12\x12\n\nlabel_name\x18\x04 \x01(\t\"2\n\x0eImportResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2_\n\x0c\x44\x61taImporter\x12O\n\x0fImportMusicData\x12\x1e.datatransfer.MusicDataRequest\x1a\x1c.datatransfer.ImportResponseb\x06proto3')



_MUSICDATAREQUEST = DESCRIPTOR.message_types_by_name['MusicDataRequest']
_IMPORTRESPONSE = DESCRIPTOR.message_types_by_name['ImportResponse']
MusicDataRequest = _reflection.GeneratedProtocolMessageType('MusicDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _MUSICDATAREQUEST,
  '__module__' : 'data_transfer_pb2'
  # @@protoc_insertion_point(class_scope:datatransfer.MusicDataRequest)
  })
_sym_db.RegisterMessage(MusicDataRequest)

ImportResponse = _reflection.GeneratedProtocolMessageType('ImportResponse', (_message.Message,), {
  'DESCRIPTOR' : _IMPORTRESPONSE,
  '__module__' : 'data_transfer_pb2'
  # @@protoc_insertion_point(class_scope:datatransfer.ImportResponse)
  })
_sym_db.RegisterMessage(ImportResponse)

_DATAIMPORTER = DESCRIPTOR.services_by_name['DataImporter']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MUSICDATAREQUEST._serialized_start=37
  _MUSICDATAREQUEST._serialized_end=143
  _IMPORTRESPONSE._serialized_start=145
  _IMPORTRESPONSE._serialized_end=195
  _DATAIMPORTER._serialized_start=197
  _DATAIMPORTER._serialized_end=292
# @@protoc_insertion_point(module_scope)
