# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import data_transfer_pb2 as data__transfer__pb2


class DataImporterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ImportMusicData = channel.stream_unary(
                '/datatransfer.DataImporter/ImportMusicData',
                request_serializer=data__transfer__pb2.MusicDataRequest.SerializeToString,
                response_deserializer=data__transfer__pb2.ImportResponse.FromString,
                )


class DataImporterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ImportMusicData(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataImporterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ImportMusicData': grpc.stream_unary_rpc_method_handler(
                    servicer.ImportMusicData,
                    request_deserializer=data__transfer__pb2.MusicDataRequest.FromString,
                    response_serializer=data__transfer__pb2.ImportResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'datatransfer.DataImporter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataImporter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ImportMusicData(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/datatransfer.DataImporter/ImportMusicData',
            data__transfer__pb2.MusicDataRequest.SerializeToString,
            data__transfer__pb2.ImportResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
