
exporter:
  sqlite_db_path: "music_data.db"

importer:
  host: "192.168.100.3"
  port: 5000

security:
  ca_cert: "../certificates/ca.pem"
  client_cert: "../certificates/client.csr"
  client_key: "../certificates/client.key"