# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import control_pb2 as proto_dot_control__pb2


class TempControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetRange = channel.unary_unary(
                '/control.TempControl/SetRange',
                request_serializer=proto_dot_control__pb2.Range.SerializeToString,
                response_deserializer=proto_dot_control__pb2.Empty.FromString,
                )


class TempControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TempControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetRange': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRange,
                    request_deserializer=proto_dot_control__pb2.Range.FromString,
                    response_serializer=proto_dot_control__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'control.TempControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TempControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/control.TempControl/SetRange',
            proto_dot_control__pb2.Range.SerializeToString,
            proto_dot_control__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class HumidityControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetRange = channel.unary_unary(
                '/control.HumidityControl/SetRange',
                request_serializer=proto_dot_control__pb2.Range.SerializeToString,
                response_deserializer=proto_dot_control__pb2.Empty.FromString,
                )


class HumidityControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HumidityControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetRange': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRange,
                    request_deserializer=proto_dot_control__pb2.Range.FromString,
                    response_serializer=proto_dot_control__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'control.HumidityControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HumidityControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/control.HumidityControl/SetRange',
            proto_dot_control__pb2.Range.SerializeToString,
            proto_dot_control__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class VideoControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ApplyFilter = channel.unary_unary(
                '/control.VideoControl/ApplyFilter',
                request_serializer=proto_dot_control__pb2.FilterRequest.SerializeToString,
                response_deserializer=proto_dot_control__pb2.Empty.FromString,
                )


class VideoControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ApplyFilter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VideoControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ApplyFilter': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyFilter,
                    request_deserializer=proto_dot_control__pb2.FilterRequest.FromString,
                    response_serializer=proto_dot_control__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'control.VideoControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VideoControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ApplyFilter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/control.VideoControl/ApplyFilter',
            proto_dot_control__pb2.FilterRequest.SerializeToString,
            proto_dot_control__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
