# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/control.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/control.proto\x12\x07\x63ontrol\"!\n\x05Range\x12\x0b\n\x03min\x18\x01 \x01(\x01\x12\x0b\n\x03max\x18\x02 \x01(\x01\"\x18\n\x05\x45mpty\x12\x0f\n\x07message\x18\x01 \x01(\t\"$\n\rFilterRequest\x12\x13\n\x0b\x66ilter_type\x18\x01 \x01(\t29\n\x0bTempControl\x12*\n\x08SetRange\x12\x0e.control.Range\x1a\x0e.control.Empty2=\n\x0fHumidityControl\x12*\n\x08SetRange\x12\x0e.control.Range\x1a\x0e.control.Empty2E\n\x0cVideoControl\x12\x35\n\x0b\x41pplyFilter\x12\x16.control.FilterRequest\x1a\x0e.control.Emptyb\x06proto3')



_RANGE = DESCRIPTOR.message_types_by_name['Range']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_FILTERREQUEST = DESCRIPTOR.message_types_by_name['FilterRequest']
Range = _reflection.GeneratedProtocolMessageType('Range', (_message.Message,), {
  'DESCRIPTOR' : _RANGE,
  '__module__' : 'proto.control_pb2'
  # @@protoc_insertion_point(class_scope:control.Range)
  })
_sym_db.RegisterMessage(Range)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'proto.control_pb2'
  # @@protoc_insertion_point(class_scope:control.Empty)
  })
_sym_db.RegisterMessage(Empty)

FilterRequest = _reflection.GeneratedProtocolMessageType('FilterRequest', (_message.Message,), {
  'DESCRIPTOR' : _FILTERREQUEST,
  '__module__' : 'proto.control_pb2'
  # @@protoc_insertion_point(class_scope:control.FilterRequest)
  })
_sym_db.RegisterMessage(FilterRequest)

_TEMPCONTROL = DESCRIPTOR.services_by_name['TempControl']
_HUMIDITYCONTROL = DESCRIPTOR.services_by_name['HumidityControl']
_VIDEOCONTROL = DESCRIPTOR.services_by_name['VideoControl']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RANGE._serialized_start=32
  _RANGE._serialized_end=65
  _EMPTY._serialized_start=67
  _EMPTY._serialized_end=91
  _FILTERREQUEST._serialized_start=93
  _FILTERREQUEST._serialized_end=129
  _TEMPCONTROL._serialized_start=131
  _TEMPCONTROL._serialized_end=188
  _HUMIDITYCONTROL._serialized_start=190
  _HUMIDITYCONTROL._serialized_end=251
  _VIDEOCONTROL._serialized_start=253
  _VIDEOCONTROL._serialized_end=322
# @@protoc_insertion_point(module_scope)
