connection:
  socket:
    host: 192.168.100.10
    port: 5000
  queue:
    type: rabbitmq
    host: 192.168.100.10
    port: 5672
    user: guest
    password: guest
    queue_name: data_queue
    exchange: data_exchange
    routing_key: data_key

db:
  sqlite:
    path: nonnormalized.db
  postgres:
    host: localhost
    port: 5432
    user: postgres
    password: postgres
    dbname: normalized_music_db