connection:
  socket:
    host_data: 192.168.148.9
    host_key: 192.168.148.9
    port: 5000
  queue:
    type: rabbitmq
    host_data: 192.168.148.9
    host_key: 192.168.148.8
    port: 5672
    user: admin
    password: admin
    queue_key: key_queue
    queue_data: data_queue
    exchange_key: key_exchange
    exchange_data: data_exchange
    routing_key: key_key
    routing_data: data_key

db:
  sqlite:
    path: nonnormalized.db
  postgres:
    host: localhost
    port: 5433
    user: postgres
    password: postgres
    dbname: musicdb