connection:
  socket:
    host_data: 192.168.148.9
    host_key: 192.168.148.8
    port: 5000
  queue:
    type: rabbitmq
    host_data: 192.168.148.9
    host_key: 192.168.148.8
    port: 5672
    user: admin
    password: admin
    queue_name: data_queue
    exchange: data_exchange
    routing_key: data_key

db:
  sqlite:
    path: nonnormalized.db
  postgres:
    host: localhost
    port: 5433
    user: postgres
    password: postgres
    dbname: musicdb