connection:
  socket:
    host_data: 192.168.100.3
    host_key: 192.168.100.10
    port: 5000
  queue:
    type: rabbitmq
    host_data: localhost
    host_key: localhost
    port: 5672
    user: guest
    password: guest
    queue_name: data_queue
    exchange: data_exchange
    routing_key: data_key

db:
  sqlite:
    path: nonnormalized.db
  postgres:
    host: localhost
    port: 5433
    user: postgres
    password: postgres
    dbname: musicdb